# Generated by Django 5.0.3 on 2024-03-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=200)),
                ('data_partida', models.DateTimeField()),
                ('durcacao', models.DurationField()),
                ('distancia', models.BigIntegerField()),
                ('preco', models.BigIntegerField()),
                ('detalhes', models.TextField()),
            ],
        ),
    ]
